name: merci_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - pandas
    - matplotlib
    - shapely
    - pillow
    - scikit-image
    - scipy
    - jupyterlab
    - ipykernel
    - zarr
    - tifffile
    - pyyaml
    - affine6p
